export const GET_CHARACTERS_ERROR = 'GET_CHARACTERS_ERROR';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';

export const GET_USERS_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USERS_ERROR = 'GET_USER_ERROR';

export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_ERROR = 'GET_USER_BY_ID_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
