export const GET_CHARACTERS_ERROR = 'GET_CHARACTERS_ERROR';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';

export const GET_USERS_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USERS_ERROR = 'GET_USER_ERROR';
